# The name of your Worker
name = "contact-form-handler"

# Specifies that this is a JavaScript Worker
type = "javascript"

# Replace with your Cloudflare account ID
account_id = "1ec5c1080c7b333a86aeffc30ce4f17d"

# Set to false for production deployment on Cloudflare Pages
workers_dev = false

[vars]
# Set this to the email address that should receive the contact form submissions
RECEIVER_EMAIL = "${RECEIVER_EMAIL}"

# Set this to the email address that will appear as the sender of the notifications
SENDER_EMAIL = "${SENDER_EMAIL}"

# The route for your API endpoint
route = "https://cf-contactform.pages.dev/api/contact"

main = "worker.js"

compatibility_date = "2023-05-18"

[build]
command = "npm run build"

[build.upload]
format = "service-worker"

[site]
bucket = ".output/public"
entry-point = "worker.js"

# Add this new section for Pages configuration
[pages]
pages_build_output_dir = ".output/public"

[env.production]
routes = [
  { pattern = "/api/contact", script = "worker.js" }
]
